---
- name: Ensure zsh is installed
  package: 
    name: zsh
    state: present

- name: Ensure oh-my-zsh installs directory exists
  file:
    path: '{{ zsh_installs_path }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'

- name: Download oh-my-zsh install script
  get_url:
    url: '{{ zsh_repo_url }}'
    dest: '{{ zsh_installs_path }}/install.sh'
    mode: '0755'

- name: Install oh-my-zsh
  ansible.builtin.shell: 'sh {{ zsh_installs_path }}/install.sh --unattended'
  args:
    executable: /usr/bin/sh
  become_user: '{{ ubuntu_user }}'

- name: Customize and Set Oh-My-Zsh Theme
  ansible.builtin.shell: '{{ item }}'
  args:
    executable: /usr/bin/bash
  loop: '{{ custom_setting_list }}'

- name: Download oh-my-zsh dark dircolors
  get_url:
    url: '{{ zsh_dircolors_url }}'
    dest: '{{ ubuntu_user_home }}/.dircolors'
    mode: '0755'
  become_user: '{{ ubuntu_user }}'

- name: Configure zsh to use dark dircolors
  lineinfile:
    path: '{{ zshrc_file_path }}'
    line: 'eval `dircolors ~/.dircolors`'
    insertbefore: '^source'

- name: Install zsh custom plugins
  ansible.builtin.git: 
    repo: '{{ zsh_custom_repo_url }}/{{ item }}.git'
    dest: '{{ zsh_plugins_path }}/{{ item }}'
  loop: '{{ zsh_custom_plugins }}'
  become_user: '{{ ubuntu_user }}'

- name: Merge plugins list
  set_fact:
    zsh_plugins_list: '{{ zsh_native_plugins + zsh_custom_plugins }}'

- name: Enable all plugins
  lineinfile:
    path: '{{ zshrc_file_path }}'
    line: 'plugins=({{ item }})'
    insertafter: '^plugins'
  loop: '{{ zsh_plugins_list }}'
  
- name: Add aliases to zsh
  blockinfile:
    path: '{{ zshrc_file_path }}'
    block: |
      alias gcl="git clone"
      alias gbr="git branch"
      alias gco="git chekout"
      alias gad="git add --all"
      alias gcm="git commit -m"
      alias gpl="git pull"
      alias gps="git push"
      alias gst="git status"
      alias ghst='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
    insertafter: 'EOF'

- name: "Set zsh as default shell for {{ ubuntu_user }}"
  ansible.builtin.shell: 'chsh -s $(which zsh)'
  args:
    executable: /usr/bin/bash
  become: yes